name: yori_sport_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_ui_auth: ^1.16.0
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/pictures/logo.png
    - assets/svgs/newCart.svg
    - assets/svgs/cart.svg
  uses-material-design: true
  fonts:
    - family: Yori
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
