// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuuo8OOs4x-Of6dMc-7acZb5c6P1RdLU',
    appId: '1:97022070620:web:e105ed2cf156da500dbb99',
    messagingSenderId: '97022070620',
    projectId: 'yori-sport',
    authDomain: 'yori-sport.firebaseapp.com',
    storageBucket: 'yori-sport.firebasestorage.app',
    measurementId: 'G-093ZXN7WWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-djfppWnbGmNRNE_lcWJ_9zvpfq97LQ',
    appId: '1:97022070620:android:b6b104de3a1ebdbb0dbb99',
    messagingSenderId: '97022070620',
    projectId: 'yori-sport',
    storageBucket: 'yori-sport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTcUoZTh47V6t0Rbu5mm2HIqGWSjnqB8',
    appId: '1:97022070620:ios:51625f4d1a0407590dbb99',
    messagingSenderId: '97022070620',
    projectId: 'yori-sport',
    storageBucket: 'yori-sport.firebasestorage.app',
    iosBundleId: 'com.example.yoriSportApp',
  );

}